CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(55)                             NOT NULL,
    password     VARCHAR(25)                             NOT NULL,
    companies_id BIGINT                                  NOT NULL,
    role_id      BIGINT                                  NOT NULL,
    access_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);


ALTER TABLE users
    ADD CONSTRAINT uc_users_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ACCESS FOREIGN KEY (access_id) REFERENCES access (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_COMPANIES FOREIGN KEY (companies_id) REFERENCES companies (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);