CREATE TABLE companies
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_companies PRIMARY KEY (id)
);

ALTER TABLE companies
    ADD CONSTRAINT uc_companies_name UNIQUE (name);