CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(15)                             NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

INSERT INTO roles (id, name)
VALUES (1, 'admin');

INSERT INTO roles (id, name)
VALUES (2, 'company admin');

INSERT INTO roles (id, name)
VALUES (3, 'accountant');

INSERT INTO roles (id, name)
VALUES (4, 'user')