create table users_cards
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      bigint
        constraint users_cards_users_id_fk
            references users,
    cards_number bigint
        constraint users_cards_cards_number_fk
            references cards,
    constraint pk_users_cards
        primary key (id)
);
