CREATE TABLE companies
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255)                            NOT NULL,
    status VARCHAR(10) DEFAULT 'ACTIVE'            NOT NULL,
    CONSTRAINT pk_companies PRIMARY KEY (id)
);

ALTER TABLE companies
    ADD CONSTRAINT uc_companies_name UNIQUE (name);

INSERT INTO companies(name)
VALUES ('Owner of platform');
