CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(15)                             NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

INSERT INTO roles (name)
VALUES ('admin');

INSERT INTO roles (name)
VALUES ('moderator');

INSERT INTO roles (name)
VALUES ('accountant');

INSERT INTO roles (name)
VALUES ('user')