ALTER TABLE users
    DROP CONSTRAINT uc_users_name;

ALTER TABLE users
    DROP CONSTRAINT FK_USERS_ON_ACCESS;

ALTER TABLE users
    DROP CONSTRAINT FK_USERS_ON_COMPANIES;

ALTER TABLE users
    DROP CONSTRAINT FK_USERS_ON_ROLE;

DROP TABLE users;
