create schema test;

CREATE TABLE test.companies
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255)                            NOT NULL,
    status VARCHAR(10) DEFAULT 'ACTIVE'            NOT NULL,
    CONSTRAINT pk_companies PRIMARY KEY (id)
);

create table test.cards
(
    number     BIGINT      NOT NULL,
    status     VARCHAR(20) NOT NULL,
    type       VARCHAR(10) NOT NULL,
    pay_system VARCHAR(10) NOT NULL,
    company_id BIGINT,
    balance    decimal,
    CONSTRAINT pk_cards PRIMARY KEY (number)
);
ALTER TABLE cards
    ADD CONSTRAINT FK_CARDS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);